name: Build and Test with Maven in Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check Career Availability
        run: sudo docker compose run --rm test mvn test -D cucumber.options="--tags @CareerTi8mCareerAvailability"
